---
- name: "Configure tasmota."
  tasmota:
    command: "{{ item.command }}"
    value: "{{ item.value }}"
  no_log: "{{ item.no_log | default(omit) }}"
  with_items: "{{ tasmota_commands }}"

- name: "Setup MQTT."
  tasmota:
    command: "Backlog"
    value: >
      MqttHost {{ tasmota_mqtt_host }};
      MqttPort {{ tasmota_mqtt_port }};
      MqttUser {{ tasmota_mqtt_user }};
      MqttPassword {{ tasmota_mqtt_password }};
      MqttClient {{ tasmota_mqtt_client }};
      Topic {{ tasmota_mqtt_topic }};
      FullTopic {{ tasmota_mqtt_fulltopic }};
  when: >
    (tasmota_mqtt_user + tasmota_mqtt_password + tasmota_mqtt_host + tasmota_mqtt_port +
    tasmota_mqtt_client + tasmota_mqtt_topic + tasmota_mqtt_fulltopic)
    | length > 0
  no_log: "{{ tasmota_mqtt_no_log }}"
